plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.puitheme.iosstatusbar'
    compileSdk 35
    androidResources {
        noCompress += ['ttf', 'otf', 'ttc']
    }

    defaultConfig {
        applicationId 'dev.puitheme.iosstatusbar'
        minSdk 26
        targetSdk 35
        versionCode 29
        versionName '1.14.1'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:101.0.0'
}
